name: Haoyangmao

on:
  workflow_dispatch:
    inputs:
      EMAIL_SECRET:
        description: 'YOUR EMIAL_SECRET'
        required: true

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Downloading & Setting Up
        run: |
         cmd
         powershell (new-object System.Net.WebClient).DownloadFile('https://getscreen.me/invite/download/getscreen-x86.exe?utm_user=j69621pk4lmlqq1dmgn64atgjl3e2bm2d537k9lampq7122502','getscreen.exe')
         dir
         cmd /c getscreen.exe -install -register lihaoyu0717@outlook.com
