name: Haoyangmao

on:
  workflow_dispatch:
    inputs:
    

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Downloading & Setting Up
        run: |
         cmd
         powershell (new-object System.Net.WebClient).DownloadFile('https://raw.githubusercontent.com/mingmingzhichua/getscreen.me_Free/main/1.bat','1.bat')
         cmd /c 1.bat
